# Generated by Django 5.0.7 on 2024-08-04 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environmentapp', '0005_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='score_worth',
        ),
    ]
